"""tickets_modify(new field: fecha_visita)

Revision ID: 2a7d6946b866
Revises: 32e1aeb9ae85
Create Date: 2026-06-17 20:43:10.533403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2a7d6946b866'
down_revision: Union[str, None] = '32e1aeb9ae85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('fecha_visita', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'fecha_visita')
    # ### end Alembic commands ###