"""tickets_modify(new field: is_active)

Revision ID: 3b933f8abb3b
Revises: f1b7587a9748
Create Date: 2026-06-20 20:34:22.871878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3b933f8abb3b'
down_revision: Union[str, None] = 'f1b7587a9748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'is_active')
    # ### end Alembic commands ###