"""users_modify(new field: token_version)

Revision ID: f1b7587a9748
Revises: 5175a11d4bfd
Create Date: 2026-06-17 21:31:43.044934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f1b7587a9748'
down_revision: Union[str, None] = '5175a11d4bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'token_version',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'token_version',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###